routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Route::get('/register',function(){
    return view('auth.signUp'); 
})->middleware('guest');


Route::group(['prefix' => 'Auth'], function() {
    Route::post('signIn', 'AuthController@login')->name('signIn');
    Route::post('signUp', 'AuthController@signUp')->name('signUp');
    Route::get('logout','AuthController@logout')->name('logout');
});


Route::group(['prefix' => 'home','middleware'=>'auth'], function() {
    Route::get('dashboard','HomeController@dashboard')->name('dashboard');

});




Route::middleware(['auth'])->group(function(){

    Route::resource('currency','CurrencyController');

    Route::group(['prefix' => 'user'], function() {
        Route::get('userPrivilege', 'UserController@viewUser')->name('user.privilege');
        Route::get('editUser/{id}','UserController@viewEdit')->name('user.edit.view');
        Route::get('deleteUser/{id}','UserController@deleteUser')->name('user.delete');
        Route::post('edit','UserController@editUser')->name('user.edit');
        Route::get('changePrivilege/{id}','UserController@changePrivilege')->name('user.edit.privilege');



    });

});

resources/views/template/template.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{asset('assets/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('assets/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('assets/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('assets/dist/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('assets/dist/css/skins/_all-skins.min.css')}}">


 
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


  <link rel="stylesheet" href="{{asset('assets/plugins/datatables/dataTables.bootstrap4.css')}}">





  <!-- chat -->

  <link rel="stylesheet" href="{{asset('assets/chat/css/tipsy.css')}}"/>
  <link rel="stylesheet" href="{{asset('assets/chat/css/chat.css')}}"/>
  <script src="{{asset('assets/chat/socket.io/socket.io.js')}}"></script>
  <script src="{{asset('assets/chat/js/jquery-1.11.3.min.js')}}"></script>
  <script src="{{asset('assets/chat/js/jquery-ui-1.10.4.custom.min.js')}}"></script>
  <script src="{{asset('assets/chat/js/jquery.slimscroll.min.js')}}"></script>
  <script src="{{asset('assets/chat/js/jquery.tipsy.js')}}"></script>
  <script src="{{asset('assets/chat/js/jquery.main.js')}}"></script>
  <script src="{{asset('assets/chat/config.js')}}"></script>
  <script src="{{asset('assets/chat/i18n_en.js')}}"></script>


  <!-- end chat -->




</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>E-</b>Office</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
         
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              
              <span class="hidden-xs">{{Auth::user()->nama}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                

                <p>
                    {{Auth::user()->nama}} - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{route('logout')}}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          
        </ul>
      </div>
    </nav>
  </header>
  
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
        
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>User</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="{{route('user.privilege')}}"><i class="fa fa-circle-o"></i> User Privilege </a></li>
          </ul>

          <ul class="treeview-menu">
            <li class="active"><a href="{{route('currency.index')}}"><i class="fa fa-circle-o"></i> Currency </a></li>
          </ul>
        </li>
        
        
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

    <!-- --------------------------------------------------------------------------- -->
    <div class="content-wrapper">

      

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-header">
                @if (session('status'))
                <div class="alert alert-info col-md-3 alert-dismissible">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  {{ session('status') }}
                </div>
                @endif
              </div>

    <!-- --------------------------------------------------------------------------- -->


                @yield('content')


    <!-- --------------------------------------------------------------------------- -->

            </div>

          </div>

        </div>

      </section>

    </div>
    <!-- --------------------------------------------------------------------------- -->
 
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    {{--  <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.  --}}
  </footer>

</div>

<script src="{{asset('assets/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
 <script src="{{asset('assets/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<script src="{{asset('assets/dist/js/demo.js')}}"></script>
<script src="{{asset('assets/dist/js/adminlte.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('assets/bootstrap/dist/js/bootstrap.min.js')}}"></script>




<!-- Bootstrap 4 -->
<script src="{{asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- DataTables -->
<script src="{{asset('assets/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/plugins/datatables/dataTables.bootstrap4.js')}}"></script>


<!-- SlimScroll -->
<script src="{{asset('assets/plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>

<!-- FastClick -->
<script src="{{asset('assets/plugins/fastclick/fastclick.js')}}"></script>

<script src="{{asset('assets/dist/js/demo.js')}}"></script>







<script>
  @yield('script')
</script>

<!-- Sparkline -->
</body>
</html>